import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Promenade Wine & Spirits',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div className="flex flex-col min-h-screen bg-fixed bg-center bg-cover" style={{ backgroundImage: "url('')" }}>
      <div className="flex-grow">
        <div className="max-w-[75%] mx-auto">
          <div className="container mx-auto">
            {/* <Navbar /> */}
          </div>
          <div>{children}</div>
       
        </div>
      </div>
    </div>
  );
}
